# https://github.com/ghdl/ghdl/blob/99b542c849311c92e87e2c70d283de133c9d4093/.github/workflows/push.yml#L56-L102

name: build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { system: MSYS,   os: windows-latest,  shell: 'msys2 {0}' },
          { system: Ubuntu, os: ubunutu-latest,  shell: bash        },
          { system: OSX,    os: macos-latest,    shell: bash        }
        ]

    env:
      MSYSTEM: MSYS
      GIT_CONFIG_NOSYSTEM: true
      TESTSUITE_FLAGS_PLUS: -k testdir

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Init MSYS2-System
        if: matrix.os = 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MSYS
          install: git base base-devel msys2-devel
      - name: Init OSX-System
        if: matrix.os = 'macos-latest'
        # https://formulae.brew.sh/formula/
        run: brew install autoconf automake gettext texinfo
      - name: Init Ubuntu-System
        if: matrix.os = 'ubuntu-latest'
        run: brew install autoconf automake gettext texinfo
      - name: Require git-clone without EOL changes
        # ... otherwise BUILD (autoconf.texi and other documentation friends) fwill fail.
        run: |
          git config --global core.autocrlf false
          git config --global --list
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Configuration
        run: |
          autoreconf -vfi
          mkdir -p build
          cd build
          ../configure -C
      - name: Run Build
        if: ${{ success() }}
        run: make
        working-directory: build
      - name: Run Testsuite
        if: ${{ success() }}
        run: make check TESTSUITEFLAGS='-j16 ${{ env.TESTSUITE_FLAGS_PLUS }}' || make check TESTSUITEFLAGS='--recheck -v -x -d -j16 ${{ env.TESTSUITE_FLAGS_PLUS }}'
        working-directory: build
      - name: Generate Artifacts upon Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.system }}-failure
          path: |
            build/config.*
            build/tests/**
