# https://github.com/ghdl/ghdl/blob/99b542c849311c92e87e2c70d283de133c9d4093/.github/workflows/push.yml#L56-L102

name: build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  msys2:
    runs-on: windows-latest
    env:
      MSYSTEM: MSYS
      GIT_CONFIG_NOSYSTEM: true

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Init MSYS2-System
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MSYS
          install: >-
            git
            base
            base-devel
            msys2-devel
      - name: Require git-clone without EOL changes
        # ... otherwise BUILD (autoconf.texi and other documentation friends) fwill fail.
        run: |
          git config --global core.autocrlf false
          git config --global --list
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run Configuration
        run: |
          autoreconf -vfi
          mkdir -p build
          cd build
          ../configure -C
      - name: Run Build
        if: ${{ success() }}
        run: make -j1
        working-directory: build
      - name: Run Testsuite
        if: ${{ success() }}
        run: make check TESTSUITEFLAGS='-j8 -k testdir' || make check TESTSUITEFLAGS='--recheck -j8 -k testdir -v -x -d'
        working-directory: build
      - name: Generate Artifacts upon Failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failure
          path: |
            build/config.*
            build/tests/**
